CREATE TABLE CLIENTE(
    ID BIGINT PRIMARY KEY,
    NOME VARCHAR(128) NOT NULL
);

CREATE TABLE MODULO(
    ID BIGINT PRIMARY KEY,
    NOME VARCHAR(128) NOT NULL
);

CREATE TABLE TICKET (
    ID BIGINT PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    ID_CLIENTE BIGINT,
    ID_MODULO BIGINT,
    DATA_ABERTURA TIMESTAMP NOT NULL,
    DATA_ENCERRAMENTO TIMESTAMP,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ID_MODULO) REFERENCES MODULO(ID)
);

CREATE SEQUENCE SEQ_CLIENTE;
CREATE SEQUENCE SEQ_MODULO;
CREATE SEQUENCE SEQ_TICKET;

ALTER TABLE CLIENTE
ALTER COLUMN ID SET DEFAULT nextval('SEQ_CLIENTE');

ALTER TABLE MODULO
ALTER COLUMN ID SET DEFAULT nextval('SEQ_MODULO');

ALTER TABLE TICKET
ALTER COLUMN ID SET DEFAULT nextval('SEQ_TICKET');