INSERT INTO CLIENTE(ID,NOME)
VALUES(1,'Apple Inc.');

INSERT INTO CLIENTE(ID,NOME)
VALUES(2,'Google');

INSERT INTO CLIENTE(ID,NOME)
VALUES(3,'Microsoft');

INSERT INTO CLIENTE(ID,NOME)
VALUES(4,'Tesla');

INSERT INTO CLIENTE(ID,NOME)
VALUES(5,'SpaceX');

INSERT INTO MODULO(ID,NOME)
VALUES(1,'Finaneiro');

INSERT INTO MODULO(ID,NOME)
VALUES(2,'Vendas');

INSERT INTO MODULO(ID,NOME)
VALUES(3,'Expedição');

INSERT INTO MODULO(ID,NOME)
VALUES(4,'Foguetes');